@baseURL = http://localhost:3030
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzM4MTk0NzdjYzAxYjg5YmE1YmZjY2EiLCJlbWFpbCI6ImthbGxlQGFyY2FkYS5maSIsImlhdCI6MTY2NDYyMDg3NywiZXhwIjoxNjY0NzA3Mjc3fQ.E_TNhJKwLjaf3SthPzBmhxprGKEPf_tZlxZdzJ0wRFY

###
GET {{baseURL}}/cabins/
Content-Type: application/json
Authorization: {{token}}

###

GET {{baseURL}}/cabins/6337fdf26d66462d7cadaf54
Content-Type: application/json
Authorization: {{token}}

###

DELETE  {{baseURL}}/cabins/633815a8f66a66dcb4db0722
Content-Type: application/json
Authorization: {{token}}


###

POST {{baseURL}}/cabins/
Content-Type: application/json
Authorization: {{token}}

{
    "cabin": "Villa kallesdasa",
    "location": "esboasdasdas",
    "price": 10002

}

###

PATCH  {{baseURL}}/cabins/633815a8f66a66dcb4db0722
Content-Type: application/json
Authorization: {{token}}

{
    "price": 10000
}